# Generated by Django 3.2 on 2023-02-15 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favourites', '0002_alter_favourites_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='product',
        ),
        migrations.AddField(
            model_name='favourites',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
