# Generated by Django 3.2 on 2023-02-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0003_auto_20230215_0850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
