# Generated by Django 3.2 on 2023-02-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
