# Generated by Django 3.2 on 2023-02-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='products/'),
        ),
    ]
