# Generated by Django 3.2 on 2023-02-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
