# Generated by Django 3.2 on 2023-03-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_on']},
        ),
    ]
